services:
  - type: web
    name: whatsapp-job-bot
    env: python
    plan: free
    runtime: python-3.12.0
    buildCommand: python --version && pip install --upgrade pip && pip install -r requirements.txt && python -m playwright install chromium
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
    healthCheckPath: /
    # Add your environment variables in Render dashboard:
    # SUPABASE_URL
    # SUPABASE_KEY
    # TWILIO_SID
    # TWILIO_TOKEN
    # TWILIO_WHATSAPP_NUMBER
    # MPESA_CONSUMER_KEY
    # MPESA_CONSUMER_SECRET
    # MPESA_SHORTCODE
    # MPESA_ENV
